const icons=[`<path d="m3 17 6-9 4 5 3-3 5 7M3 21h18M7 3h4"/>`,`<path d="M3 7h18M5 7l3 13h8l3-13M8 12h8M9 16h6M10 3v4m4-4v4"/>`,`<path d="m8 3-4 18M16 3l4 18M12 3v4m0 3v4m0 3v4"/>`,`<path d="M3 7h6v6h6v4h6M3 11h2v6h6v4h10M17 3v7m-3-3 3 3 3-3"/>`,`<path d="M12 3S5 11 5 15a7 7 0 0 0 14 0c0-4-7-12-7-12ZM9 16a3 3 0 0 0 3 3"/>`,`<path d="M3 5h6v6h6V5h6M3 9h2v6h5v6h4v-6h5V9h2"/>`];
const modules=[{name:'Earthworks',subs:['Temp Earth Drain']},{name:'Erosion and Sediment Control',subs:['Silt Trap','Sediment Basin']},{name:'Internal Roads',subs:[]},{name:'Drainage System',subs:[]},{name:'Water Reticulation',subs:[]},{name:'Sewerage Network',subs:[]}];
const icon=i=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[i]}</svg>`;
const shortNames=['Earthworks','Erosion','Roads','Drainage','Water','Sewerage'];
document.querySelector('#discipline-grid').innerHTML=modules.map((m,i)=>`<a href="#module/${i}" aria-label="${m.name}">${icon(i)}<b>${shortNames[i]}</b></a>`).join('');
const grid=document.querySelector('#module-grid'),nav=document.querySelector('#nav');
modules.forEach((m,i)=>{nav.insertAdjacentHTML('beforeend',`<a href="#module/${i}"><span>${icon(i)}</span>${m.name}</a>`);grid.insertAdjacentHTML('beforeend',`<a class="module-card" href="#module/${i}" aria-label="Open ${m.name} module"><div class="card-top"><span class="module-icon">${icon(i)}</span></div><h3>${m.name}</h3><p>${m.subs.length?m.subs.join(' <span aria-hidden="true">·</span> '):'The design scope will be developed.'}</p><div class="card-bottom"><span class="status">Awaiting details</span><span aria-hidden="true">↗</span></div></a>`)});
function render(){const match=location.hash.match(/^#module\/([0-5])(?:\/([0-1]))?$/);const detail=document.querySelector('#detail');document.querySelector('.heading').hidden=!match;document.querySelector('#dashboard').hidden=!!match;detail.hidden=!match;document.querySelectorAll('#nav a').forEach((a,index)=>{const selected=match?index===Number(match[1])+1:index===0;a.classList.toggle('active',selected);selected?a.setAttribute('aria-current','page'):a.removeAttribute('aria-current')});if(match){const i=Number(match[1]),m=modules[i],sub=match[2]!==undefined?m.subs[Number(match[2])]:null;document.querySelector('#page-title').textContent=sub||m.name;document.querySelector('#page-subtitle').textContent=sub?m.name:'Preliminary planning module / Master Plan';if(i===0&&sub==='Temp Earth Drain'){EarthDrain.mount(detail);window.scrollTo(0,0);return}detail.innerHTML=`<a class="back" href="${sub?'#module/'+i:'#dashboard'}">← ${sub?'Back to '+m.name:'Back to dashboard'}</a><div class="detail-panel"><span class="status">Awaiting details</span><h2>${sub||m.name}</h2>${!sub&&m.subs.length?'<p>Components identified for this module.</p>'+m.subs.map((s,j)=>`<a class="submodule" href="#module/${i}/${j}">${s}<span>↗</span></a>`).join(''):''}<div class="empty"><h3>Design details to follow</h3><p>${sub?'Parameters, criteria, and calculation methods for '+sub+' will be added when the details are available.':'The design scope, parameters, and criteria will be completed when further information is available.'}</p><p>No calculations or design results are available at this stage.</p></div></div>`;window.scrollTo(0,0)}else{document.querySelector('#page-title').textContent='Dashboard';document.querySelector('#page-subtitle').textContent='One workspace for every master plan component.';if(location.hash==='#modules')requestAnimationFrame(()=>document.querySelector('#modules').scrollIntoView({behavior:'smooth'}))}}
window.addEventListener('hashchange',render);render();

const menuToggle=document.querySelector('.menu-toggle');
function closeMenu(){menuToggle.setAttribute('aria-expanded','false');document.querySelector('aside').classList.remove('menu-open')}
menuToggle.addEventListener('click',()=>{const open=menuToggle.getAttribute('aria-expanded')!=='true';menuToggle.setAttribute('aria-expanded',String(open));document.querySelector('aside').classList.toggle('menu-open',open)});
document.querySelector('#nav').addEventListener('click',e=>{if(e.target.closest('a'))closeMenu()});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menuToggle.getAttribute('aria-expanded')==='true'){closeMenu();menuToggle.focus()}});
window.addEventListener('hashchange',closeMenu);
